name: amazon
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  country_picker: ^2.0.20
  firebase_core: ^2.30.1
  firebase_auth: ^4.19.3
  provider: ^6.1.2
  fluttertoast: ^8.2.5
  page_transition: ^2.1.0
  persistent_bottom_nav_bar_v2: ^4.2.8
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.8.0
  uuid: ^3.0.7
  image_picker: ^0.8.8
  firebase_storage: ^11.2.2
  flutter_rating_bar: ^4.0.1
  razorpay_flutter: ^1.3.5
  motion_toast: ^2.6.8
  flutter_native_splash: ^2.4.0
  email_validator: ^2.1.17
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/carousel_slideshow/
    - assets/images/categories/
    - assets/images/offersNsponcered/
    - assets/images/todays_deals/
    - assets/images/menu_pics/

#  adaptive_icon_background: "assets/images/Icon_logo.png"
#  adaptive_icon_foreground: "assets/images/Icon_logo.png"

flutter_native_splash:
  #  color: "#ffffff"
  image: "assets/images/amazon_splash_screen.png"
