// code generated by [generate-resource-dart-code] vscode-extension.
class AssetsImages {
  static const png0 = 'assets/images/menu_pics/0.png';
  static const png10 = 'assets/images/menu_pics/10.png';
  static const png11 = 'assets/images/menu_pics/11.png';
  static const png12 = 'assets/images/menu_pics/12.png';
  static const png13 = 'assets/images/menu_pics/13.png';
  static const png14 = 'assets/images/menu_pics/14.png';
  static const png15 = 'assets/images/menu_pics/15.png';
  static const png16 = 'assets/images/menu_pics/16.png';
  static const png17 = 'assets/images/menu_pics/17.png';
  static const png1 = 'assets/images/carousel_slideshow/1.png';
  static const png2 = 'assets/images/carousel_slideshow/2.png';
  static const png3 = 'assets/images/carousel_slideshow/3.png';
  static const png4 = 'assets/images/carousel_slideshow/4.png';
  static const png5 = 'assets/images/carousel_slideshow/5.png';
  static const png6 = 'assets/images/carousel_slideshow/6.png';
  static const png7 = 'assets/images/carousel_slideshow/7.png';
  static const png8 = 'assets/images/carousel_slideshow/8.png';
  static const png9 = 'assets/images/carousel_slideshow/9.png';
  static const amazonBlackLogoPng = 'assets/images/amazon_black_logo.png';
  static const amazonLogoPng = 'assets/images/amazon_logo.png';
  static const amazonSplashScreenPng = 'assets/images/amazon_splash_screen.png';
  static const appliancesPng = 'assets/images/categories/Appliances.png';
  static const beautyPng = 'assets/images/categories/Beauty.png';
  static const boatPng = 'assets/images/offersNsponcered/boat.png';
  static const booksPng = 'assets/images/categories/Books.png';
  static const bosePng = 'assets/images/offersNsponcered/bose.png';
  static const businessPng = 'assets/images/categories/Business.png';
  static const dealsPng = 'assets/images/categories/Deals.png';
  static const electronicsPng = 'assets/images/categories/Electronics.png';
  static const fashionPng = 'assets/images/categories/Fashion.png';
  static const furniturePng = 'assets/images/categories/Furniture.png';
  static const homePng = 'assets/images/categories/Home.png';
  static const insurancePng = 'assets/images/offersNsponcered/insurance.png';
  static const kurtaPng = 'assets/images/offersNsponcered/kurta.png';
  static const miniTVPng = 'assets/images/categories/miniTV.png';
  static const mobilesPng = 'assets/images/categories/Mobiles.png';
  static const morePng = 'assets/images/categories/More.png';
  static const moviesPng = 'assets/images/categories/Movies.png';
  static const onePlusPng = 'assets/images/offersNsponcered/onePlus.png';
  static const pharmacyPng = 'assets/images/categories/Pharmacy.png';
  static const primePng = 'assets/images/categories/Prime.png';
  static const sixerPng = 'assets/images/offersNsponcered/sixer.png';
  static const sonyPng = 'assets/images/offersNsponcered/sony.png';
  static const tShirtsPng = 'assets/images/offersNsponcered/t_shirts.png';
  static const todaysDeal0Png = 'assets/images/todays_deals/todaysDeal0.png';
  static const todaysDeal1Png = 'assets/images/todays_deals/todaysDeal1.png';
  static const todaysDeal2Png = 'assets/images/todays_deals/todaysDeal2.png';
  static const todaysDeal3Png = 'assets/images/todays_deals/todaysDeal3.png';
  static const topsPng = 'assets/images/offersNsponcered/tops.png';
  static const travelPng = 'assets/images/categories/Travel.png';
  static const viewAllPng = 'assets/images/offersNsponcered/view_all.png';
}

class AssetsSvgs {}
