// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwzl_zrrxokqMaIgJEvtuORDXI8ID7HeQ',
    appId: '1:901909518862:web:470d3705ff358013123a5f',
    messagingSenderId: '901909518862',
    projectId: 'sw2-project-9bc47',
    authDomain: 'sw2-project-9bc47.firebaseapp.com',
    storageBucket: 'sw2-project-9bc47.appspot.com',
    measurementId: 'G-Q2CV8YZYGH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdK6fObxQD7Zn1CUvIX1aR_AJZeYgKnuI',
    appId: '1:901909518862:android:ec3ccbbc460d264a123a5f',
    messagingSenderId: '901909518862',
    projectId: 'sw2-project-9bc47',
    storageBucket: 'sw2-project-9bc47.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4EYdTPltmm7RQx2WD7bG2Q_9LiDcuiHU',
    appId: '1:901909518862:ios:03c8fb493d1b341c123a5f',
    messagingSenderId: '901909518862',
    projectId: 'sw2-project-9bc47',
    storageBucket: 'sw2-project-9bc47.appspot.com',
    iosBundleId: 'com.example.amazona',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4EYdTPltmm7RQx2WD7bG2Q_9LiDcuiHU',
    appId: '1:901909518862:ios:03c8fb493d1b341c123a5f',
    messagingSenderId: '901909518862',
    projectId: 'sw2-project-9bc47',
    storageBucket: 'sw2-project-9bc47.appspot.com',
    iosBundleId: 'com.example.amazona',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwzl_zrrxokqMaIgJEvtuORDXI8ID7HeQ',
    appId: '1:901909518862:web:aead17aa3dbc6bf3123a5f',
    messagingSenderId: '901909518862',
    projectId: 'sw2-project-9bc47',
    authDomain: 'sw2-project-9bc47.firebaseapp.com',
    storageBucket: 'sw2-project-9bc47.appspot.com',
    measurementId: 'G-807596JK2S',
  );
}
