// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4EBGoNefW3uKtOeaT9EJ85bOkKz4RM5U',
    appId: '1:318788694580:web:d8bb999ec2129ee8925061',
    messagingSenderId: '318788694580',
    projectId: 'a-1ecf8',
    authDomain: 'a-1ecf8.firebaseapp.com',
    storageBucket: 'a-1ecf8.appspot.com',
    measurementId: 'G-CJCK93H6HQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACxq770qmzIcOZB2jdRxJQg0vPr4tVWug',
    appId: '1:318788694580:android:f33235607228ee67925061',
    messagingSenderId: '318788694580',
    projectId: 'a-1ecf8',
    storageBucket: 'a-1ecf8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC65d4AW7eDKs8yyLrtTeIiC0qITKeS8eI',
    appId: '1:318788694580:ios:6b9f5c1ae9faffc9925061',
    messagingSenderId: '318788694580',
    projectId: 'a-1ecf8',
    storageBucket: 'a-1ecf8.appspot.com',
    iosBundleId: 'com.example.amazona',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC65d4AW7eDKs8yyLrtTeIiC0qITKeS8eI',
    appId: '1:318788694580:ios:6b9f5c1ae9faffc9925061',
    messagingSenderId: '318788694580',
    projectId: 'a-1ecf8',
    storageBucket: 'a-1ecf8.appspot.com',
    iosBundleId: 'com.example.amazona',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4EBGoNefW3uKtOeaT9EJ85bOkKz4RM5U',
    appId: '1:318788694580:web:dd7c38567df907d5925061',
    messagingSenderId: '318788694580',
    projectId: 'a-1ecf8',
    authDomain: 'a-1ecf8.firebaseapp.com',
    storageBucket: 'a-1ecf8.appspot.com',
    measurementId: 'G-J82FFQKJC7',
  );
}
